package gui;

public enum PropertyType {
	WORKSPACE_HEADING_LABEL,

	DETAILS_HEADING_LABEL,
	NAME_PROMPT,
	OWNER_PROMPT,

	ITEMS_HEADING_LABEL,

	ADD_ICON,
	ADD_ITEM_TOOLTIP,

	REMOVE_ICON,
	REMOVE_ITEM_TOOLTIP,

	MOVE_UP_ICON,
	MOVE_UP_ITEM_TOOLTIP,

	MOVE_DOWN_ICON,
	MOVE_DOWN_ITEM_TOOLTIP,

	CATEGORY_COLUMN_HEADING,
	DESCRIPTION_COLUMN_HEADING,
	START_DATE_COLUMN_HEADING,
	END_DATE_COLUMN_HEADING,
	COMPLETED_COLUMN_HEADING,


	DIMENSIONS_TITLE_LABEL,
	DIMENSION_HEIGHT_LABEL,
	DIMENSION_WIDTH_LABEL,

	CHOOSE_FILE_BUTTON,
	NEW_TITLE_LABEL,
	NEW_SUBNAME_LABEL,
	NEW_DIRECTORY_LABEL,
	NEW_COORDINATE_LABEL,
	NO_DIR_SELECTED,
	NO_FILE_SELECTED,

	SUBREGION_TITLE_LABEL,
	SUBREGION_NAME,
	SUBREGON_CAPITAL,
	SUBREGON_LEADER,
	SUBREGION_NO_PICTURE,

	OK_BUTTON,
	CANCEL_BUTTON,

	WORKSPACE_CSS,
	DIALOG_CSS
}
