package gui;

public enum PropertyType {
	WORKSPACE_HEADING_LABEL,

	DETAILS_HEADING_LABEL,
	NAME_PROMPT,
	OWNER_PROMPT,

	ITEMS_HEADING_LABEL,

	ADD_ICON,
	ADD_ITEM_TOOLTIP,

	REMOVE_ICON,
	REMOVE_ITEM_TOOLTIP,

	MOVE_UP_ICON,
	MOVE_UP_ITEM_TOOLTIP,

	MOVE_DOWN_ICON,
	MOVE_DOWN_ITEM_TOOLTIP,

	CATEGORY_COLUMN_HEADING,
	DESCRIPTION_COLUMN_HEADING,
	START_DATE_COLUMN_HEADING,
	END_DATE_COLUMN_HEADING,
	COMPLETED_COLUMN_HEADING,


	DIMENSIONS_TITLE_LABEL,
	DIMENSION_HEIGHT_LABEL,
	DIMENSION_WIDTH_LABEL,

	OK_BUTTON,
	CANCEL_BUTTON
}
